---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config2
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm




---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: test-container
              image: k8s.gcr.io/busybox
              command: [ "/bin/sh", "-c", "env" ]
              envFrom:
              - configMapRef:
                  name: special-config2
          # restartPolicy: Never
          restartPolicy: OnFailure 